"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowLeft, ArrowRight, Bell, Car, Check, CheckCircle2, ChevronRight, ClipboardList, FileText, Gauge, LayoutDashboard, Menu, Plus, Search, Settings, ShieldCheck, Upload, Users, Wrench, X } from "lucide-react";

type Stage = "Entrada"|"Documentos"|"Análise"|"Vistoria"|"Aprovação"|"Reparo"|"Concluído";
type EventItem = {id:string; member:string; phone:string; vehicle:string; plate:string; type:string; stage:Stage; owner:string; priority:"Alta"|"Normal"; created:string; docs:string[]};
const stages:Stage[]=["Entrada","Documentos","Análise","Vistoria","Aprovação","Reparo","Concluído"];
const seed:EventItem[]=[
 {id:"EV-2841",member:"Marina Costa",phone:"(62) 99821-4430",vehicle:"Jeep Renegade 2023",plate:"QWE-8H21",type:"Colisão",stage:"Análise",owner:"Camila",priority:"Alta",created:"28/08/2026",docs:["CNH.pdf","Documento-veiculo.pdf"]},
 {id:"EV-2839",member:"Rafael Nunes",phone:"(62) 99108-7731",vehicle:"Honda Civic 2020",plate:"RTA-2D09",type:"Assistência",stage:"Vistoria",owner:"Leandro",priority:"Normal",created:"28/08/2026",docs:["CNH.pdf"]},
 {id:"EV-2835",member:"Bruna Almeida",phone:"(62) 98410-0023",vehicle:"VW T-Cross 2022",plate:"GHI-4B10",type:"Vidros",stage:"Documentos",owner:"Camila",priority:"Alta",created:"27/08/2026",docs:[]},
 {id:"EV-2828",member:"Carlos Ribeiro",phone:"(62) 99661-1522",vehicle:"Toyota Corolla 2021",plate:"KLM-7C44",type:"Roubo/Furto",stage:"Aprovação",owner:"André",priority:"Alta",created:"26/08/2026",docs:["B.O.pdf","CNH.pdf"]},
 {id:"EV-2821",member:"Elisa Martins",phone:"(62) 99780-2262",vehicle:"Hyundai HB20 2024",plate:"OPA-1A73",type:"Colisão",stage:"Reparo",owner:"Leandro",priority:"Normal",created:"25/08/2026",docs:["Orçamento.pdf"]},
];
const nav=[["Dashboard",LayoutDashboard],["Esteira",Gauge],["Associados",Users],["Prestadores",Wrench],["Documentos",FileText],["Automações",Activity]] as const;
const money=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(n);

export default function Home(){
 const [view,setView]=useState("Dashboard"),[items,setItems]=useState<EventItem[]>(seed),[query,setQuery]=useState(""),[selected,setSelected]=useState<EventItem|null>(null),[modal,setModal]=useState(false),[menu,setMenu]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{const s=localStorage.getItem("veloce-events");if(s) try{setItems(JSON.parse(s))}catch{};navigator.serviceWorker?.register("/sw.js").catch(()=>{})},[]);
 useEffect(()=>{localStorage.setItem("veloce-events",JSON.stringify(items))},[items]);
 const filtered=useMemo(()=>items.filter(x=>`${x.id} ${x.member} ${x.plate} ${x.type}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const active=items.filter(x=>x.stage!=="Concluído").length, completed=items.filter(x=>x.stage==="Concluído").length;
 function create(form:FormData){const n=items.length+2842;const event:EventItem={id:`EV-${n}`,member:String(form.get("member")),phone:String(form.get("phone")),vehicle:String(form.get("vehicle")),plate:String(form.get("plate")).toUpperCase(),type:String(form.get("type")),stage:"Entrada",owner:String(form.get("owner")),priority:form.get("priority") as "Alta"|"Normal",created:new Date().toLocaleDateString("pt-BR"),docs:[]};setItems(v=>[event,...v]);setModal(false);setSaved(true);setTimeout(()=>setSaved(false),2200)}
 function move(id:string,dir:number){setItems(v=>v.map(x=>{if(x.id!==id)return x;const i=Math.max(0,Math.min(stages.length-1,stages.indexOf(x.stage)+dir));const next={...x,stage:stages[i]};if(selected?.id===id)setSelected(next);return next}))}
 function addDocs(id:string,files:FileList|null){if(!files)return;const names=[...files].map(f=>f.name);setItems(v=>v.map(x=>x.id===id?{...x,docs:[...x.docs,...names]}:x));setSelected(s=>s?{...s,docs:[...s.docs,...names]}:s)}
 return <div className="neo-app">
  <aside className={`neo-side ${menu?"show":""}`}><div className="neo-logo"><span><ShieldCheck/></span><div><b>Veloce</b><small>Operations</small></div></div><button className="close-menu" onClick={()=>setMenu(false)}><X/></button><p className="section-label">CENTRAL OPERACIONAL</p><nav>{nav.map(([n,I])=><button key={n} className={view===n?"on":""} onClick={()=>{setView(n);setMenu(false)}}><I/><span>{n}</span>{n==="Esteira"&&<em>{active}</em>}</button>)}</nav><div className="side-health"><div><i/><span>Todos os serviços online</span></div><b>Sincronizado agora</b><small>Supabase · n8n · BI</small></div><button className="side-config"><Settings/>Configurações</button></aside>
  <main className="neo-main"><header className="neo-top"><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div className="top-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar evento, associado ou placa"/><kbd>⌘ K</kbd></div><div className="top-tabs">{["Dashboard","Esteira","Associados"].map(x=><button className={view===x?"active":""} onClick={()=>setView(x)} key={x}>{x}</button>)}</div><button className="bell"><Bell/><i/></button><div className="user"><span>DM</span><div><b>Débora Martins</b><small>Administradora</small></div></div></header>
  <section className="neo-content">
   <div className="welcome"><div><small>VISÃO GERAL DA OPERAÇÃO</small><h1>{view}</h1><p>Controle completo da jornada do associado, do primeiro contato à conclusão.</p></div><button className="glow-btn" onClick={()=>setModal(true)}><Plus/>Novo evento</button></div>
   {view==="Dashboard"&&<Dashboard items={items} active={active} completed={completed} onOpen={setSelected}/>}
   {view==="Esteira"&&<Pipeline items={filtered} onOpen={setSelected}/>}
   {view==="Associados"&&<Associates items={filtered} onOpen={setSelected}/>}
   {view==="Prestadores"&&<Providers/>}
   {view==="Documentos"&&<Documents items={items}/>}
   {view==="Automações"&&<Automations/>}
  </section></main>
  {modal&&<NewEvent onClose={()=>setModal(false)} onCreate={create}/>}
  {selected&&<Detail item={selected} onClose={()=>setSelected(null)} onMove={d=>move(selected.id,d)} onFiles={f=>addDocs(selected.id,f)}/>}
  {saved&&<div className="toast"><CheckCircle2/>Evento criado e salvo</div>}
 </div>
}

function Dashboard({items,active,completed,onOpen}:{items:EventItem[],active:number,completed:number,onOpen:(x:EventItem)=>void}){
 const monthly=[28,36,31,48,54,42,69,58,75,67,82,91];
 return <><div className="kpis"><article className="hero-kpi"><small>EVENTOS EM OPERAÇÃO</small><strong>{active}</strong><span><b>+12,8%</b> no mês</span><Car/></article><article><small>VALOR SOB GESTÃO</small><strong>{money(438500)}</strong><span>Estimativa dos eventos ativos</span></article><article><small>CONCLUÍDOS</small><strong>{completed+184}</strong><span><b>92%</b> dentro do SLA</span></article><article><small>PENDÊNCIAS CRÍTICAS</small><strong>07</strong><span className="warn">3 vencem hoje</span><AlertTriangle/></article></div>
 <div className="neo-grid"><article className="neo-card chart-card"><div className="card-title"><div><small>DESEMPENHO MENSAL</small><h3>Eventos processados</h3></div><span className="live"><i/> Dados ao vivo</span></div><div className="chart"><div className="chart-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="chart-bars">{monthly.map((n,i)=><div key={i}><i style={{height:`${n}%`}} className={i===11?"hot":""}/><small>{["Set","Out","Nov","Dez","Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago"][i]}</small></div>)}</div></div></article>
 <article className="neo-card pulse"><div className="card-title"><div><small>SAÚDE OPERACIONAL</small><h3>SLA em tempo real</h3></div><Activity/></div><div className="ring"><div><b>92%</b><small>Excelente</small></div></div><ul><li><i className="ok"/>Dentro do prazo <b>77</b></li><li><i className="risk"/>Em risco <b>5</b></li><li><i className="late"/>Atrasados <b>2</b></li></ul></article></div>
 <article className="neo-card recent"><div className="card-title"><div><small>PRIORIDADE OPERACIONAL</small><h3>Eventos que precisam de atenção</h3></div><button>Ver esteira <ChevronRight/></button></div><div className="event-list">{items.slice(0,5).map(x=><button key={x.id} onClick={()=>onOpen(x)}><span className={`status-dot ${x.priority.toLowerCase()}`}/><div><b>{x.id} · {x.member}</b><small>{x.vehicle} · {x.plate}</small></div><em>{x.type}</em><span className="stage-pill">{x.stage}</span><strong>{x.owner}</strong><ChevronRight/></button>)}</div></article></>
}
function Pipeline({items,onOpen}:{items:EventItem[],onOpen:(x:EventItem)=>void}){return <div className="pipeline">{stages.map(stage=><section key={stage}><header><span>{stage}</span><b>{items.filter(x=>x.stage===stage).length}</b></header>{items.filter(x=>x.stage===stage).map(x=><button key={x.id} onClick={()=>onOpen(x)}><small>{x.id}</small><b>{x.member}</b><span>{x.vehicle}</span><footer><em>{x.type}</em><i className={x.priority.toLowerCase()}>{x.priority}</i></footer></button>)}</section>)}</div>}
function Associates({items,onOpen}:{items:EventItem[],onOpen:(x:EventItem)=>void}){return <article className="neo-card data-card"><div className="card-title"><div><small>BASE DE ASSOCIADOS</small><h3>Associados com eventos</h3></div></div><div className="member-grid">{items.map(x=><button key={x.id} onClick={()=>onOpen(x)}><span>{x.member.split(" ").map(n=>n[0]).slice(0,2).join("")}</span><div><b>{x.member}</b><small>{x.phone}</small></div><em>{x.vehicle}<br/>{x.plate}</em><ChevronRight/></button>)}</div></article>}
function Providers(){return <div className="provider-grid">{[["Auto Prime","Funilaria e pintura","4,9","12"],["Glass Pro","Vidros automotivos","4,8","8"],["Reboque 24h","Assistência e remoção","4,7","16"]].map(x=><article className="neo-card" key={x[0]}><Wrench/><small>PRESTADOR CREDENCIADO</small><h3>{x[0]}</h3><p>{x[1]}</p><div><span>Nota <b>{x[2]}</b></span><span>Em execução <b>{x[3]}</b></span></div><button>Ver desempenho <ArrowRight/></button></article>)}</div>}
function Documents({items}:{items:EventItem[]}){const docs=items.flatMap(x=>x.docs.map(d=>({event:x.id,member:x.member,name:d})));return <article className="neo-card data-card"><div className="card-title"><div><small>ARQUIVOS DA OPERAÇÃO</small><h3>Documentos recebidos</h3></div><span className="live"><i/>{docs.length} arquivos</span></div><div className="doc-list">{docs.map((d,i)=><div key={i}><FileText/><div><b>{d.name}</b><small>{d.event} · {d.member}</small></div><span>Validado</span></div>)}</div></article>}
function Automations(){return <div className="auto-grid">{[["Evento criado","Enviar confirmação ao associado","Ativa"],["Documento pendente","Cobrar automaticamente em 24h","Ativa"],["SLA em risco","Alertar gestor responsável","Ativa"],["Evento concluído","Enviar pesquisa de satisfação","Pausada"]].map(x=><article className="neo-card" key={x[0]}><div><Activity/><span className={x[2]==="Ativa"?"on":""}>{x[2]}</span></div><small>GATILHO</small><h3>{x[0]}</h3><p>{x[1]}</p><button>Editar fluxo <ArrowRight/></button></article>)}</div>}
function NewEvent({onClose,onCreate}:{onClose:()=>void,onCreate:(f:FormData)=>void}){return <div className="overlay"><form className="modal" action={onCreate}><button type="button" className="modal-x" onClick={onClose}><X/></button><small className="modal-label">NOVO ATENDIMENTO</small><h2>Abrir evento</h2><p>Cadastre o associado e inicie a esteira operacional.</p><div className="form-grid"><label>Nome do associado<input required name="member" placeholder="Nome completo"/></label><label>WhatsApp<input required name="phone" placeholder="(00) 00000-0000"/></label><label>Veículo<input required name="vehicle" placeholder="Marca, modelo e ano"/></label><label>Placa<input required name="plate" placeholder="ABC-1D23"/></label><label>Tipo<select name="type"><option>Colisão</option><option>Roubo/Furto</option><option>Assistência</option><option>Vidros</option></select></label><label>Responsável<select name="owner"><option>Camila</option><option>Leandro</option><option>André</option></select></label><label>Prioridade<select name="priority"><option>Normal</option><option>Alta</option></select></label></div><footer><button type="button" onClick={onClose}>Cancelar</button><button className="glow-btn" type="submit"><Plus/>Criar evento</button></footer></form></div>}
function Detail({item,onClose,onMove,onFiles}:{item:EventItem,onClose:()=>void,onMove:(d:number)=>void,onFiles:(f:FileList|null)=>void}){const idx=stages.indexOf(item.stage);return <div className="detail-layer"><aside className="detail"><button className="modal-x" onClick={onClose}><X/></button><small className="modal-label">EVENTO {item.id}</small><h2>{item.member}</h2><p>{item.vehicle} · {item.plate}</p><div className="detail-meta"><span>{item.type}</span><span className={item.priority.toLowerCase()}>{item.priority}</span><span>{item.owner}</span></div><div className="stepper">{stages.map((s,i)=><div key={s} className={i<idx?"done":i===idx?"current":""}><i>{i<idx?<Check/>:i+1}</i><span>{s}</span></div>)}</div><div className="detail-actions"><button disabled={idx===0} onClick={()=>onMove(-1)}><ArrowLeft/>Voltar etapa</button><button disabled={idx===stages.length-1} className="glow-btn" onClick={()=>onMove(1)}>Avançar etapa<ArrowRight/></button></div><section className="files"><header><div><small>DOCUMENTOS</small><h3>Arquivos do evento</h3></div><label><Upload/>Anexar<input type="file" multiple onChange={e=>onFiles(e.target.files)}/></label></header>{item.docs.length?item.docs.map((d,i)=><div key={i}><FileText/><span>{d}</span><em>Recebido</em></div>):<p>Nenhum documento anexado.</p>}</section></aside></div>}
