from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def shell(title,subtitle,content,active=''):
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="../app/globals.css"><title>{title}</title></head><body><div class="app-stage">
<header class="app-header"><div class="header-inner"><button class="mobile-menu">≡</button><button class="brand"><span class="brand-mark"><img src="../public/veloce-mark.svg"></span><span><strong>Veloce</strong><small>Central operacional</small></span></button><nav class="desktop-nav"><button>Visão geral</button><button class="{'active' if active=='Esteira' else ''}">Esteira</button><button class="{'active' if active=='Associados' else ''}">Associados</button><button class="{'active' if active=='Rede' else ''}">Rede</button><button class="{'active' if active=='Documentos' else ''}">Documentos</button><button class="{'active' if active=='Rotinas' else ''}">Rotinas</button></nav><div class="header-actions"><button class="header-search">Buscar <kbd>⌘K</kbd></button><button class="header-icon">!</button><button class="agent-header-button {'active' if active=='Agente' else ''}"><span class="agent-header-icon">◇</span><span>Agente</span></button><button class="profile-button"></button></div></div></header>
<main class="app-shell"><div class="content-shell"><header class="page-header"><div><span class="page-kicker">Central operacional</span><h1>{title}</h1><p>{subtitle}</p></div>{('<div class="page-actions"><button class="button button-primary">Novo evento</button></div>' if active=='Esteira' else '<div class="page-actions"><button class="button button-primary">Novo associado</button></div>' if active=='Associados' else '')}</header>{content}</div></main>
<nav class="mobile-nav"><button>Início</button><button class="{'active' if active=='Esteira' else ''}">Esteira</button><button class="{'active' if active=='Rotinas' else ''}">Rotinas</button><button class="{'active' if active=='Agente' else ''}">Agente</button><button>Mais</button></nav></div></body></html>'''

stage_buttons=''.join(f'<button><span>{n}</span><strong>{c}</strong><i style="width:{w}%"></i></button>' for n,c,w in [('Entrada',2,30),('Documentos',2,40),('Análise',2,48),('Vistoria',2,55),('Aprovação',1,65),('Reparo',1,72),('Concluído',2,85)])
rows=''.join(f'<button class="table-row"><span data-label="Evento"><strong>EV-28{48-i}</strong><small>há {4+i*5} min</small></span><span data-label="Associado"><strong>{name}</strong><small>São Paulo, SP</small></span><span data-label="Veículo"><strong>{car}</strong><small>RTA-8D2{i}</small></span><span data-label="Etapa">Documentos</span><span data-label="SLA"><span class="status {"status-danger" if i==1 else "status-warning"}">{"Atrasado" if i==1 else "Risco"}</span></span><span data-label="Responsável">Larissa</span><span>→</span></button>' for i,(name,car) in enumerate([('Marina Costa','Jeep Compass'),('Helena Duarte','Hyundai Creta'),('Rafael Prado','Toyota Corolla')]))
pipeline=f'''<div class="workspace"><section class="stage-overview">{stage_buttons}</section><article class="panel table-panel"><div class="table-toolbar"><div><h2>Eventos ativos</h2><span>Fila priorizada por SLA</span></div><label class="inline-search"><input placeholder="Buscar evento, nome ou placa"></label><button class="filter-button">Filtros</button></div><div class="data-table"><div class="table-row table-head"><span>Evento</span><span>Associado</span><span>Veículo</span><span>Etapa</span><span>SLA</span><span>Responsável</span><span></span></div>{rows}</div></article></div>'''
(ROOT/'qa/esteira.html').write_text(shell('Esteira operacional','Acompanhe cada evento até a conclusão, sem perder o SLA.',pipeline,'Esteira'))

assoc_rows=''.join(f'<button><span class="associate-avatar">{initial}</span><span><strong>{name}</strong><small>AS-19{i} · São Paulo, SP</small></span><span><strong>{car}</strong><small>RTA-8D2{i}</small></span><span>(11) 99999-88{i}8</span><span class="status">Ativo</span><span>→</span></button>' for i,(initial,name,car) in enumerate([('MC','Marina Costa','Jeep Compass'),('RP','Rafael Prado','Toyota Corolla'),('BF','Bianca Freitas','Honda HR-V')],52))
associates=f'''<div class="workspace"><section class="summary-strip"><div><span>Ativos</span><strong>2.458</strong></div><div><span>Pendentes</span><strong>36</strong></div><div><span>Novos no mês</span><strong>84</strong></div><div><span>Atualizações hoje</span><strong>17</strong></div></section><section class="associate-focus-grid"><article class="panel associate-focus"><div class="associate-focus-avatar">MC</div><div><span class="panel-kicker">Associada em acompanhamento</span><h2>Marina Costa</h2><p>São Paulo, SP</p><div class="associate-focus-meta"><span>Jeep Compass · RTA-8D21</span><span>(11) 99942-3810</span></div></div><span class="status">Ativo</span></article><article class="panel associate-quick"><span class="panel-kicker">Gestão da base</span><h2>Cadastro direto, sem etapas escondidas.</h2><button class="button button-primary">Novo associado</button></article></section><article class="panel list-panel"><div class="section-head"><h2>Base de associados</h2></div><div class="associate-list">{assoc_rows}</div></article></div>'''
(ROOT/'qa/associados.html').write_text(shell('Associados','Cadastros, veículos e situação de cada associado.',associates,'Associados'))

provider_cards=''.join(f'''<article class="provider-card"><div class="provider-head"><span class="provider-icon">▣</span><span class="status">Dentro</span></div><h2>{n}</h2><p>{spec} · {city}</p><dl><div><dt>Carga</dt><dd>{load}%</dd></div><div><dt>Prazo</dt><dd>2 dias</dd></div><div><dt>Nota</dt><dd>4,9</dd></div><div><dt>Ativos</dt><dd>18</dd></div></dl><div class="capacity"><span><b>Capacidade</b><b>{100-load}% livre</b></span><i><b style="width:{load}%"></b></i></div><button class="button">Distribuir evento</button></article>''' for n,spec,city,load in [('Auto Prime Centro','Funilaria e pintura','São Paulo, SP',62),('Vistocar Leste','Vistoria técnica','São Paulo, SP',41),('Oficina Norte','Mecânica e elétrica','Guarulhos, SP',78),('CheckAuto Campinas','Vistoria e laudos','Campinas, SP',36)])
rede=f'''<div class="workspace"><section class="provider-summary"><div><span>Prestadores ativos</span><strong>24</strong></div><div><span>Vagas hoje</span><strong>11</strong></div><div><span>Prazo médio</span><strong>2,1 dias</strong></div></section><section class="provider-grid">{provider_cards}</section></div>'''
(ROOT/'qa/rede.html').write_text(shell('Rede credenciada','Capacidade, prazo e distribuição entre prestadores.',rede,'Rede'))

doc_rows=''.join(f'<button><span class="doc-icon">□</span><span><strong>{item}</strong><small>{name} · EV-28{i}</small></span><span>{age}</span><span class="status {tone}">{status}</span><span>→</span></button>' for i,(item,name,age,status,tone) in enumerate([('CNH do condutor','Marina Costa','18 min','Pendente','status-warning'),('Fotos do veículo','Paula Meireles','1 h 12 min','Atrasado','status-danger'),('Boletim de ocorrência','Lívia Ramos','2 h','Em análise',''),('Comprovante de endereço','Henrique Dias','3 h','Recebido','')],48))
docs=f'''<div class="workspace"><section class="document-summary"><div><span>Pendentes</span><strong>8</strong></div><div><span>Atrasados</span><strong>3</strong></div><div><span>Em análise</span><strong>12</strong></div><div><span>Recebidos hoje</span><strong>19</strong></div></section><article class="panel list-panel"><div class="section-head"><h2>Pendências por evento</h2></div><div class="document-list">{doc_rows}</div></article></div>'''
(ROOT/'qa/documentos.html').write_text(shell('Documentos','Pendências e conferências organizadas por evento.',docs,'Documentos'))

routine_cards=''.join(f'<article class="routine-card {"featured" if i==1 else ""}"><span class="routine-icon">{i+1}</span><div><h2>{title}</h2><p>{note}</p></div><button><span>Executar</span><span>→</span></button></article>' for i,(title,note) in enumerate([('Cobrar documentos','8 pendências'),('Revisar SLAs','6 em atenção'),('Distribuir rede','4 prestadores'),('Triar entradas','2 novos eventos'),('Gerar relatório','Resumo da rodada'),('Revisar cadastros','3 incompletos')]))
routines=f'''<div class="workspace"><section class="routine-hero"><div><span class="panel-kicker">Execução recorrente</span><h2>Escolha a tarefa e avance direto para a ação.</h2></div><button class="button button-dark">Abrir agente</button></section><section class="routine-grid">{routine_cards}</section></div>'''
(ROOT/'qa/rotinas.html').write_text(shell('Rotinas operacionais','Ações recorrentes prontas para executar com segurança.',routines,'Rotinas'))

agent='''<div class="agent-layout"><section class="panel agent-main"><header class="agent-top"><span class="agent-symbol">◇</span><div><span class="panel-kicker">Agente Veloce</span><h2>Comandos operacionais</h2></div><span class="agent-ready"><i></i>Pronto</span></header><div class="prompt-row"><button>Revisar SLAs</button><button>Cobrar documentos</button><button>Localizar associado</button></div><div class="message-list"><div class="message assistant"><span>Há 5 itens em atenção. Posso abrir a fila, localizar um associado ou organizar documentos.</span></div><div class="message user"><span>Abra os SLAs atrasados.</span></div><div class="message assistant"><span>Consulta registrada. A fila crítica está pronta para revisão.</span></div></div><form class="agent-input"><span>□</span><input placeholder="Digite uma ação ou pergunta"><button><span>Executar</span><span>→</span></button></form></section><aside class="agent-side"><article class="critical-panel"><span class="panel-kicker">Fila crítica</span><strong>3</strong><p>itens para decisão imediata</p><div><button><span><strong>Helena Duarte</strong><small>EV-2844 · Aprovação</small></span><span class="status status-danger">Atrasado</span></button><button><span><strong>Marina Costa</strong><small>EV-2848 · Documentos</small></span><span class="status status-warning">Risco</span></button></div></article><article class="panel agent-actions-card"><div class="section-head"><h2>Atalhos</h2></div><button><span>Gerar resumo da rodada</span><span>→</span></button><button><span>Organizar documentos</span><span>→</span></button><button><span>Consultar capacidade da rede</span><span>→</span></button></article></aside></div>'''
(ROOT/'qa/agente.html').write_text(shell('Agente operacional','Consulte a operação e execute ações sem trocar de tela.',agent,'Agente'))
print('generated')
